theme: jekyll-theme-minimal
#title: Nicola G. Kriefall
#description: PhD candidate<br><a href="http://sites.bu.edu/davieslab/">Davies Marine Population Genomics Lab</a><br>Boston University<br>Boston, MA<br><a href="https://scholar.google.com/citations?user=CHwW2yoAAAAJ&hl=en&oi=ao">Google Scholar Profile</a>
#logo: <img src="images/logo.jpg">
