theme: jekyll-theme-minimal
title: Nicola G. Kriefall
description: PhD candidate<br><a href="http://sites.bu.edu/davieslab/">Davies Marine Population Genomics Lab</a><br>Boston University<br>Boston, MA, USA
logo: /images/headshot_crop.jpeg
